from reportlab import *
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.platypus import Paragraph, Table, TableStyle, Image, Frame, Spacer, PageBreak, BaseDocTemplate, PageTemplate, SimpleDocTemplate, Flowable
from PIL import Image
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet, TA_CENTER
from reportlab.graphics import barcode
import datetime




class expanseReportHead(Flowable):

    def __init__(self):
        Flowable.__init__(self)

    #----------------------------------------------------------------------
    def draw(self):
        """
        draw the floable
        """

        barcode_value = "1234567890"
        barcode39 = barcode.createBarcodeDrawing('EAN13', value = barcode_value,barWidth=0.3*mm,barHeight=10*mm)

        barcode39.drawOn(self.canv,0,0)



MARGIN_SIZE = 5 * mm
PAGE_SIZE = A4

now = datetime.datetime.now()

# c = canvas.Canvas("hello.pdf")
# c.drawString(9*cm, 19*cm, "Hello World!")

pdfdoc = 'hello.pdf'

pdf_doc = SimpleDocTemplate(pdfdoc, pagesize = PAGE_SIZE,
    leftMargin = MARGIN_SIZE, rightMargin = MARGIN_SIZE,
    topMargin = MARGIN_SIZE, bottomMargin = MARGIN_SIZE)


styles=getSampleStyleSheet()
styleN = styles['Normal']
styleH = styles['Heading1']

# data = [['', '', '', 'Grand Total', '' , pFooterGrandTotal]]

text_data = ["S. No", "Vendor ID", "Vendor", "Description",
             "Total amount", "Date", "Invoice ID"]

d = []
font_size = 8
centered = ParagraphStyle(name="centered", alignment=TA_CENTER)
for text in text_data:
    ptext = "<font size=%s><b>%s</b></font>" % (font_size, text)
    p = Paragraph(ptext, centered)
    d.append(p)

data = [d]
line_num = 1
formatted_line_data = []
for x in range(15):
    line_data = [str(line_num),"V101", "Sagar motors", "Tata zest", "73090",
                 "12 June", "123456"]

    for item in line_data:
        ptext = "<font size=%s>%s</font>" % (font_size-1, item)
        p = Paragraph(ptext, centered)
        formatted_line_data.append(p)
    data.append(formatted_line_data)
    formatted_line_data = []
    line_num += 1

t = Table(data, colWidths=[40, 100, 100, 150, 50, 40, 70])

ts = TableStyle([('LINEABOVE',(0,0),(-1,0),0.25,colors.gray),
            ('LINEABOVE',(0,1),(-1,1),0.25,colors.gray),
        ])

t.setStyle(ts)

#add some flowables

headingPara = 'Daily expanses'
pSrc = '''
story.append(Spacer(2.5,0.75*cm))
<font size=10>
<strong>Generated by:</strong> %s<br/><br/>
</font>
''' % ('Manoj Kumar')

story = []
story.append(Paragraph(headingPara,styleH))
story.append(Paragraph('%s'%(now.strftime("%d-%B-%Y - %H:%M %p")) ,styleN))
story.append(Paragraph(pSrc , styleN))

expHead = expanseReportHead()
story.append(expHead)

story.append(t)

pdf_doc.build(story)

# c.showPage()
# c.save()
